package org.example;

import org.example.runner.SigmaRunner;

public class CompilerApp {
    private static final String SAMPLE_CODE = """
                int x = 10;
                println("Hello, Sigma!");
                int y = x + 10;
                """;

    public static void main(String[] args) {
        SigmaCompiler compiler = new SigmaCompiler();
        SigmaRunner runner = new SigmaRunner();

        if (args.length == 0) {
            // Interactive mode - simple example
            System.out.println("Sigma Compiler - Interactive Mode");

            // Step 1: Compile
            CompilationResult result = compiler.compile(SAMPLE_CODE);

            // Step 2: Handle compilation result
            if (!result.isSuccessful()) {
                System.err.println("Compilation failed:");
                System.err.println(result.getAllMessagesAsString());
                return;
            }

            // Debug output
            System.out.println("Compilation successful!");
            System.out.println("Generated bytecode length: " + result.getBytecode().length);
            System.out.println("Class name: " + result.getClassName());

            // Step 3: Execute (separate responsibility)
            try {
                System.out.println("Starting execution...");
                runner.run(result);
                System.out.println("Execution completed.");
            } catch (Exception e) {
                System.err.println("Execution failed: " + e.getMessage());
                e.printStackTrace();
            }

        } else {
            // File mode
            for (String filename : args) {
                System.out.println("Compiling: " + filename);

                // Step 1: Compile file
                CompilationResult result = compiler.compileFile(filename);

                // Step 2: Handle compilation result
                if (!result.isSuccessful()) {
                    System.err.println("Compilation of " + filename + " failed:");
                    System.err.println(result.getAllMessagesAsString());
                    continue; // Try next file
                }

                // Step 3: Execute (separate responsibility)
                System.out.println("Executing: " + filename);
                try {
                    runner.run(result);
                } catch (Exception e) {
                    System.err.println("Execution of " + filename + " failed: " + e.getMessage());
                }
            }
        }
    }

}
